image: gitpod/workspace-full
vscode:
  extensions:
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
